# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

let
  options = builtins.mapAttrs (fsType: options: { inherit fsType options; }) {
    btrfs = [ ];
    vfat = [ ];
    ntfs = [ "rw" "uid=1000" ];
  };

in with options; {
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7e7c2d18-e9db-4d4b-8432-70f8f5c705ee";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C617-C7CB";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d2a64d3d-dc23-414b-83bb-b675188e7611";
    fsType = "btrfs";
  };
  fileSystems."/mnt/media" = {
    device = "/dev/sdc1";
    fsType = "btrfs";
  };
  fileSystems."/mnt/tv" = { device = "/dev/sdd1"; } // ntfs;

  swapDevices =
    [{ device = "/dev/disk/by-uuid/7700f7df-5d2a-4046-b070-2b2c4b97cfa7"; }];

  nix.maxJobs = lib.mkDefault 8;
}
